Add Settings Page and bring GraphiQL IDE and WPGraphQL Insights into the core plugin
wp-graphql/wp-graphql pull request #1462
Opened 2020-09-16 22:26 UTC by jasonbahl

This PR does the following: 

- Adds GraphiQL IDE to the main WPGraphQL plugin (deprecates the need for separate [WPGraphiQL](https://github.com/wp-graphql/wp-graphiql) plugin)
- Adds GraphQL Settings Page with API to register more fields and field sections
- Adds Query Logs and Tracing to the main WPGraphQL plugin (deprecates the need for separate [WPGraphQL Insights](https://github.com/wp-graphql/wp-graphql-insights) plugin)

## GraphiQL IDE

WPGraphQL now has GraphiQL IDE built in to WPGraphQL! 

GraphiQL IDE is an incredibly useful tool for working with GraphQL APIs, and now it's available to all users of WPGraphQL without needing to find and install a separate plugin. 

With WPGraphQL Active, there is now an Admin Menu for GraphQL, and within that menu is "GraphiQL IDE" link

![Screen Shot 2020-09-16 at 3 10 44 PM](https://user-images.githubusercontent.com/1260765/93392896-cd9ca280-f82e-11ea-9147-abb726c637de.png)

There's also an Admin Bar short-link for GraphiQL IDE: 

![Screen Shot 2020-09-16 at 3 11 42 PM](https://user-images.githubusercontent.com/1260765/93392988-ef962500-f82e-11ea-8eb9-3cb527a3991f.png)

Clicking either link will open GraphiQL in the WP Admin: 

![Screen Shot 2020-09-16 at 3 12 19 PM](https://user-images.githubusercontent.com/1260765/93393042-050b4f00-f82f-11ea-918b-4e38bffbe4b3.png)

You can now browse the WPGraphQL Schema and test Queries and Mutations all from within the WordPress Dashboard. 

## Settings Page (and API)
WPGraphQL now has a settings page where some common configurations can be set, without needing to touch code. 

In the Admin Menu, there's now a "GraphQL > Settings" link

![Screen Shot 2020-09-16 at 3 17 20 PM](https://user-images.githubusercontent.com/1260765/93393410-b8744380-f82f-11ea-9e57-f190003aa816.png)

Clicking that will take you to a Settings Page: 

![Screen Shot 2020-09-16 at 3 18 05 PM](https://user-images.githubusercontent.com/1260765/93393483-d346b800-f82f-11ea-8cf1-631404bb75ed.png)

### Settings Overview

These settings can be used to accomplish some common tasks with WPGraphQL that previously required code (filters/constants) to accomplish. 

- **GraphQL Endpoint**: You can now change the endpoint to be something other than `/graphql`.
- **Enable GraphiQL IDE**: You can enable/disable GraphiQL IDE in the Admin. Now that GraphiQL is bundled, you can turn it off if you prefer not to have it. 
- **Delete Data on Deactivation**: You can opt in or out of having any data WPGraphQL stores be deleted when WPGraphQL is de-activated. Things like the settings for this settings page get stored in the database. You can choose to keep data (for example temporary de-activations) or delete all data on de-activation to keep your data clean.
- **Enable GraphQL Debug Mode**: When errors occur in GraphQL requests, the default message is "Internal Server Error" to ensure implementation details are not leaked to the public. Enabling GraphQL Debug Mode shows more detailed messages, allowing developers to identify issues more quickly. 
- **Enable GraphQL Tracing**: Enabling tracing will track performance of the entire request and each field within the request. The trace data will be returned as part of the "extensions" portion of the GraphQL response, alongside the data. This feature was previously part of WPGraphQL Insights, but can now be enabled by checking this setting. Trace data can be helpful for identifying bottlenecks (slow resolvers)
- **Tracing Role:** With Tracing Enabled, it can be limited to a certain roles. Only the selected role (or all) will see the trace data in results of GraphQL requests
- **Enable Query Logs**: Enabling Query Logs will return MySQL Query logs in the "extensions" portion of the GraphQL response. This is essentially like Query Monitor for WPGraphQL. You can see the specific MySQL queries being executed to resolve GraphQL requests.
- **Query Log Role**: If Query Logs are enabled, they will execute, but the results can be limited to a specific user role, or all user roles (public requests allowed). 

### Settings API

Along with the Settings Page, there are some basic APIs to allow 3rd party plugins to easily add GraphQL Settings. 

#### register_graphql_settings_section

This function should be used within the `graphql_register_settings` action, and allows new Settings Sections to be registered to the Settings Page. 

**usage:**

```php
add_action( 'graphql_register_settings', function() {
	register_graphql_settings_section( 'graphql_my_section', [
		'title' => __( 'My Section', 'your-textdomain' ),
	]);
});
```

This will add a new section to the settings page like so: 

![Screen Shot 2020-09-16 at 3 40 56 PM](https://user-images.githubusercontent.com/1260765/93395358-050d4e00-f833-11ea-96ed-2ca48ab3e0cd.png)

#### register_graphql_settings_field

This function will register a new settings field to the specified settings section: 

**usage:**

```php
add_action( 'graphql_register_settings', function() {
	register_graphql_settings_field( 'graphql_my_section', [
		'name'    => 'my_field',
		'label'   => __( 'My Field', 'your-textdomain' ),
		'desc'    => __( 'Your field description...', 'your-textdomain' ),
		'type'    => 'text',
		'default' => "my default value...",
	]);
});
```

This registers a text field named with the "My Field" label to the "graphql_my_section" section. 

![Screen Shot 2020-09-16 at 3 44 37 PM](https://user-images.githubusercontent.com/1260765/93395675-8a90fe00-f833-11ea-8ae3-c356069e02ae.png)

#### register_graphql_settings_fields

This allows multiple settings fields to be registered to a section. 

**usage:**

```php
add_action( 'graphql_register_settings', function() {
	register_graphql_settings_section( 'graphql_new_section', [
		'title' => __( 'New Section', 'your-textdomain' ),
	] );
	register_graphql_settings_fields( 'graphql_new_section', [
		[
			'name'    => 'text',
			'label'   => __( 'Text Input', 'wedevs' ),
			'desc'    => __( 'Text input description', 'wedevs' ),
			'type'    => 'text',
			'default' => 'Title'
		],
		[
			'name'  => 'textarea',
			'label' => __( 'Textarea Input', 'wedevs' ),
			'desc'  => __( 'Textarea description', 'wedevs' ),
			'type'  => 'textarea'
		],
		[
			'name'  => 'checkbox',
			'label' => __( 'Checkbox', 'wedevs' ),
			'desc'  => __( 'Checkbox Label', 'wedevs' ),
			'type'  => 'checkbox'
		],
		[
			'name'    => 'radio',
			'label'   => __( 'Radio Button', 'wedevs' ),
			'desc'    => __( 'A radio button', 'wedevs' ),
			'type'    => 'radio',
			'options' => [
				'yes' => 'Yes',
				'no'  => 'No'
			]
		],
		[
			'name'    => 'multicheck',
			'label'   => __( 'Multile checkbox', 'wedevs' ),
			'desc'    => __( 'Multi checkbox description', 'wedevs' ),
			'type'    => 'multicheck',
			'options' => [
				'one'   => 'One',
				'two'   => 'Two',
				'three' => 'Three',
				'four'  => 'Four'
			]
		],
		[
			'name'    => 'selectbox',
			'label'   => __( 'A Dropdown', 'wedevs' ),
			'desc'    => __( 'Dropdown description', 'wedevs' ),
			'type'    => 'select',
			'default' => 'no',
			'options' => [
				'yes' => 'Yes',
				'no'  => 'No'
			]
		],
		[
			'name'    => 'password',
			'label'   => __( 'Password', 'wedevs' ),
			'desc'    => __( 'Password description', 'wedevs' ),
			'type'    => 'password',
			'default' => ''
		],
		[
			'name'    => 'file',
			'label'   => __( 'File', 'wedevs' ),
			'desc'    => __( 'File description', 'wedevs' ),
			'type'    => 'file',
			'default' => ''
		],
		[
			'name'    => 'color',
			'label'   => __( 'Color', 'wedevs' ),
			'desc'    => __( 'Color description', 'wedevs' ),
			'type'    => 'color',
			'default' => ''
		],
		[
			'name'    => 'user_role',
			'label'   => __( 'User Role', 'wp-graphql' ),
			'desc'    => __( 'Description for selecting a User Role.', 'wp-graphql' ),
			'type'    => 'user_role_select',
			'default' => "administrator",
		],
	] );
} );
```

![Screen Shot 2020-09-16 at 3 49 51 PM](https://user-images.githubusercontent.com/1260765/93396110-5964fd80-f [...]

2020-09-16 22:58 UTC, TylerBarnes commented
Awesome! :D

2020-09-17 02:09 UTC, renatonascalves requested changes
A few suggestions!

I also noted lots of opportunities to improve type casting, PHPdocs improvements, and code standardization here.

2020-09-17 02:09 UTC, renatonascalves commented on src/Utils/QueryLog.php
> +//		}
Is this comment is still valid?

2020-09-17 02:09 UTC, renatonascalves commented on src/Admin/Settings/SettingsRegistry.php
> +	function register_field( $section, $field ) {
Missing phpdoc.

2020-09-17 02:09 UTC, renatonascalves commented on src/Admin/Settings/SettingsRegistry.php
> +	public function get_field_description( $args ) {
```suggestion
	public function get_field_description( $args ): string {
```

2020-09-17 02:09 UTC, renatonascalves commented on src/Admin/Settings/Settings.php
> +
A bit of spacing here....

2020-09-17 02:09 UTC, renatonascalves commented on src/Utils/Tracing.php
> +	public function get_trace() {
```suggestion
	public function get_trace(): array {
```

2020-09-17 02:09 UTC, renatonascalves commented on src/Utils/Tracing.php
> +		return apply_filters( 'graphql_tracing_response', $trace, $this );
```suggestion
		return apply_filters( 'graphql_tracing_response', (array) $trace, $this );
```

2020-09-17 02:09 UTC, renatonascalves commented on src/Utils/Tracing.php
> +		return true;
Leftovers?

```suggestion
```

2020-09-17 02:09 UTC, renatonascalves commented on src/Utils/Tracing.php
> +	public function user_can_see_trace_data() {
```suggestion
	public function user_can_see_trace_data(): bool {
```

2020-09-17 02:09 UTC, renatonascalves commented on src/Utils/Tracing.php
> +	 * @return mixed
```suggestion
	 * @return array
```

2020-09-17 02:09 UTC, renatonascalves commented on src/Utils/Tracing.php
> +	public function return_tracing_headers( $headers ) {
```suggestion
	public function return_tracing_headers( $headers ): array {
```

2020-09-17 02:09 UTC, renatonascalves commented on src/Utils/Tracing.php
> +		return $headers;
```suggestion
		return (array) $headers;
```

2020-09-17 02:09 UTC, renatonascalves commented on src/Utils/Tracing.php
> +	 * @var
What's this variable type?

2020-09-17 02:09 UTC, renatonascalves commented on src/Utils/Tracing.php
> +	 * @var
```suggestion
	 * @var array
```

2020-09-24 22:23 UTC, merged