Add new filter for meta field order
wp-graphql/wp-graphql pull request #1546
Opened 2020-11-03 02:03 UTC by jacobarriola

What does this implement/fix? Explain your changes.
---------------------------------------------------
Adds a new filter so that consumer can handle types before the SQL query is set. There are instances where a float is being passed but the type value is set to null. This creates unexpected SQL results.

An example implementation would be something like this:

```php
/**
 * Ensure meta field type is set to decimal (float)
 */
add_filter( 'wpgraphql_cursor_ordering_field', function ( $fields, $builder, $object_cursor ) {
	// Bail if not a float
	if ( empty( strpos( $fields['value'], '.' ) ) ) {
		return $fields;
	}
	
	
	$fields['type'] = 'DECIMAL(10,' . wc_get_price_decimals() . ')';
	
	return $fields;
}, 10, 3 );
```

Does this close any currently open issues?
------------------------------------------
#1545 

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------
See issue.

2020-11-04 15:21 UTC, jacobarriola commented
@jasonbahl Do you need me to address some of these failing tests? Feels like issues outside the scope of this PR. LMK.

2020-11-06 15:10 UTC, jasonbahl commented on src/Data/Cursor/CursorBuilder.php
> +			'wpgraphql_cursor_ordering_field',
@jacobarriola can we get a docblock over the cursor explaining the params?

something like: 

```
/**
 * Filters the field used for ordering when cursors are used for pagination
 * 
 * @param array $field The field key, value, type and order 
 * @param CursorBuilder $this The CursorBuilder class
 * @param mixed null | PostObjectCursor $cursor The PostObjectCursor class
 */

2020-11-06 15:11 UTC, jasonbahl requested changes
see: https://github.com/wp-graphql/wp-graphql/pull/1546/files#r518813086

2020-11-06 16:29 UTC, jasonbahl commented
@jacobarriola it looks like the tests are failing because of some composer dependency that needs updated. I'm working on getting that fixed now.

2020-11-06 16:30 UTC, jasonbahl commented
@jacobarriola I fixed the composer issue that was messing up tests and merged it to your branch so tests are re-running now.

2020-11-06 16:35 UTC, jasonbahl commented on src/Data/Cursor/CursorBuilder.php
> +			'wpgraphql_cursor_ordering_field',
@jacobarriola upon looking at this a bit more, we also need to make sure we're escaping _after_ the filter. 

So, I think we need to change this a bit more too. 

Something like: 

```php
$field = [
  'key'   => esc_sql( $key ),
  'value' => esc_sql( $value ),
  'type'  => esc_sql( $type ),
  'order' => esc_sql( $order ),
];

$filtered_field = apply_filters( 'wpgraphql_cursor_ordering_field', $field, $this, $object_cursor );
$clean_fields = [];
if ( ! empty( $field ) && is_array( $field ) ) {
  foreach( $field as $key => $value ) {
     $clean_fields[ $key ] = esc_sql( $value );
  }
}

$this->fields = $clean_fields;

```

2020-11-06 16:35 UTC, jasonbahl commented on src/Data/Cursor/CursorBuilder.php
> +			'wpgraphql_cursor_ordering_field',
^ untested, just wrote here in Github as pseudo code, but might be legit 🤷‍♂️

2020-11-13 07:25 UTC, jasonbahl submitted a review, later dismissed

2020-11-13 07:27 UTC, jasonbahl commented on src/Data/Cursor/CursorBuilder.php
> +			'wpgraphql_cursor_ordering_field',
```suggestion
			'graphql_cursor_ordering_field',
```

2020-11-13 07:35 UTC, merged