feat: add where args to plugin connections
wp-graphql/wp-graphql pull request #2298
Opened 2022-03-14 04:07 UTC by justlevine

What does this implement/fix? Explain your changes.
---------------------------------------------------
This PR adds the ability to filter plugin connections. It builds off #895 and loosely mimics [`WP_Plugins_List_Table::prepare_items()`](https://github.com/WordPress/wordpress-develop/blob/0b800e21c311e302824e4a025946a6fdb4f6c794/src/wp-admin/includes/class-wp-plugins-list-table.php#L92)

It adds the following where args to `RootQueryToPluginConnection`:
- `search`: a keyword search across all plugin data.
- `status`:  filters by a single `PluginStatusEnum`.
- `stati`: filters by _any_ `PluginStatusEnum` in the given array.

The possible plugin stati that can be filtered are: `ACTIVE`, `DROP_IN`, `INACTIVE`, `MUST_USE`, `PAUSED`, `RECENTLY_ACTIVE`, and `UPGRADE`. On MU, we also get `NETWORK_ACTIVATED` and `NETWORK_INACTIVE`.

When no where args are set, the query will return _all_ plugins (including drop-in and MU, which were previously missing ).

Does this close any currently open issues?
------------------------------------------
#178

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------
![image](https://user-images.githubusercontent.com/29322304/158097319-79cca198-ab9a-4bfa-8448-77a11b6d0073.png)

Any other comments?
-------------------
** Needs Decision **:
- I think `PluginConnectionResolver::should_execute()` _should_ be checking `current_user_can( 'activate_plugins' )` and not the current `update_plugins` cap. `PluginConnectionResolver::get_query()` is written under the assumption it will be changed. Was checking `update_plugins` intentional or an oversight?

- The existing schema pattern is to have separate where args for a ` 'type' => 'SomeType'` and `'type' => [ 'list_of' => 'SomeType' ]` ( e.g. `status` and `stati`) even though the latter:
  - Can take a single value sans the array wrapper,
  - Almost always needs to be type checked, to convert a single value to an array, and
  - That same check + conversion is often done on a single `status` to keep the rest of the resolver DRY.
  IMO all those single-value args are unnecessary, can be removed without any loss of functionality, improving the WPGraphiQL DX and a resulting in leaner codebase + schema. Assuming you agree (I'd open a separate issue/PR) should this PR still add both args?

**Notes**:
- Filtering by `ACTIVE | INACTIVE` doesn't include network plugins (you can get both with `where : { stati : [ACTIVE, NETWORK_ACTIVATED] }` ). This differs from the backend, where network activated plugins are included in the `Active`/`Inactive` tabs. The alternative would be  a `(bool) includeNetworkPlugins` connection arg, which is bad DX.

- `NETWORK_INACTIVE` doesn't have a WP backend counterpart. It's here for DX.

- `PluginConnectionResolver::get_query()` strays from the pattern of other resolver query methods, to reduce cognitive complexity and keep things performant (ternaries over if/else, splatting to avoid multiple loops, and keeping array operations to a minimum). IDK if the existing patterns are a relic of the WP ecosystem in 2017 or style preference, but if it's the latter, a second set of eyes might be able to change the style without compromising on performance.

- Following `WP_Plugins_List_Table::prepare_items()`, `get_query()` builds the plugin data from a few sources, which means there's more fields that can be surfaced by the Plugin model. Separation of concerns stopped me from adding those fields to the schema in this PR. (The data is in this PR for simplicity, and this way devs can add the fields themselves in the interim).

- WPUnit tests *have not * been added to the PR. Its a waste of time before #2293 and #2294 are merged.

- Every time I tried to `git rebase` the original PR, my PC crashed from 3 years of commit history. Props to @t0lya should be added to the release.

Where has this been tested?
---------------------------
**Operating System:** Ubuntu 20.04 (Wsl2 + devilbox) + PHP v8.0.15

**WordPress Version:** 5.9.2

2022-04-04 21:48 UTC, justlevine commented
I added the tests for `search`, and active/inactive `status`, but i'm not sure if there is a way to test the other stati in Codeception.

2022-04-04 21:51 UTC, jasonbahl commented
@justlevine 

# Needs Discussion

## capability change

re: `update_plugins` vs `activate_plugins`: I'm not sure I recall the reasoning we chose this `update_plugins` vs `activate_plugins`. But, based on WordPress core documentation about the `activate_plugins` capability (https://wordpress.org/support/article/roles-and-capabilities/#activate_plugins) I think it would be safe to change the capability here from `update_plugins` to `activate_plugins`.

 ## single vs plural filter args

I agree that we only need the plural args. No need to have both. I think the duplication right now is largely a product of trying to map things too closely to the underlying WordPress args. 

I think the connection filters need an overhaul altogether, tbh, but for now, we can take small steps like only introducing a plural argument as it can work for singular and plural values just fine.

-----

# Notes

## get_query difference

> PluginConnectionResolver::get_query() strays from the pattern of other resolver query methods, to reduce cognitive complexity and keep things performant (ternaries over if/else, splatting to avoid multiple loops, and keeping array operations to a minimum)

There's definitely things that are a product of WP code styling / habits, but there's also some things that are maybe intentional. 

For example, even though I do use ternaries a lot, they can cause misleading code coverage reports where if/else statements make it more clear in coverage reports which cases have/have-not been tested.

ex: https://coveralls.io/builds/47988145/source?filename=src%2FData%2FLoader%2FPluginLoader.php#L41

We don't have a test that covers whether the `show_advanced_plugins` filter is true/false, but our coverage report makes it seem like both cases are covered in tests because of the ternary. 

If this were refactored as an if/else, we would have some lines that are clearly not covered by tests and might uncover some bugs we didn't know about. 

(It looks like we might have some options to overcome the coverage objection: https://phpunit.readthedocs.io/en/9.5/configuration.html#the-pathcoverage-attribute)

2022-04-04 21:55 UTC, jasonbahl commented
> I added the tests for search, and active/inactive status, but i'm not sure if there is a way to test the other stati in Codeception.

Ya... not easily, I don't think. We'd have to probably adjust how the Docker env is scaffolded. Probably something we can address later.

2022-04-04 21:56 UTC, jasonbahl commented on src/Type/Enum/PluginStatusEnum.php
> +	protected static function get_enum_values() {
you can ignore this suggestion

2022-04-04 21:58 UTC, jasonbahl requested changes

2022-04-04 21:58 UTC, jasonbahl commented on src/Type/Enum/PluginStatusEnum.php
> +				'description' => __( 'The plugin is a Must-use plugin.', 'wp-graphql' ),
```suggestion
				'description' => __( 'The plugin is a must-use plugin.', 'wp-graphql' ),
```

2022-04-04 21:58 UTC, jasonbahl approved these changes

2022-04-05 19:09 UTC, jasonbahl commented
@justlevine re: path coverage for tests, it looks like this is coming to Codeception in Codeception v5 (https://github.com/Codeception/Codeception/issues/6155)

so might be some time before we get it properly implemented in WPGraphQL.

2022-04-05 19:09 UTC, jasonbahl commented
Also, I'm not saying the code coverage objection should require this PR to be refactored. Just something to be considered.

2022-04-05 19:28 UTC, jasonbahl commented
I've opened this issue to track `path_coverage` in Codeception / wp-browser

2022-04-05 19:30 UTC, jasonbahl commented
I think the use of ternary operators in many cases is going to be fine, and we can add missing tests as chores down the road as we update coverage. 

I think it's definitely worth considering _not_ using a ternary if the implication of the if/else the ternary is deciding isn't much different. 

If the behavior is significantly different, it might be worth going with an if/else statement. 

I think the use of ternaries in this PR are probably fine.

2022-04-05 21:16 UTC, jasonbahl approved these changes

2022-04-05 21:16 UTC, merged