Add graphql_resolve_uri_query_vars for extra query vars
wp-graphql/wp-graphql pull request #2534
Opened 2022-09-22 18:23 UTC by markkelnar

What does this implement/fix? Explain your changes.
---------------------------------------------------
Add filter during the resolve_uri function to filter the request with it's extra query vars to allow a node to be returned based on the filter.

Does this close any currently open issues?
------------------------------------------
Reference [issue](https://github.com/wp-graphql/wp-graphql/issues/2515).

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Operating System:** …

**WordPress Version:** …

2022-09-23 16:30 UTC, jasonbahl commented on src/Data/NodeResolver.php
> +		$node = apply_filters( 'graphql_resolve_uri_query_vars', null, $uri, $this->context, $this->wp, $extra_query_vars );
@markkelnar When using this pattern of having a `null` and then checking if it's not null and returning, we use `graphql_pre_` as the prefix, stemming from patterns in WordPress core. 

I think this looks good, but I think we should change the name to something like: `graphql_pre_resolve_uri_with_query_vars`

2022-09-23 16:30 UTC, jasonbahl commented on src/Data/NodeResolver.php
> +		$node = apply_filters( 'graphql_resolve_uri_query_vars', null, $uri, $this->context, $this->wp, $extra_query_vars );
```suggestion
		$node = apply_filters( 'graphql_pre_resolve_uri_with_query_vars', null, $uri, $this->context, $this->wp, $extra_query_vars );
```

2022-09-23 17:19 UTC, jasonbahl approved these changes

2022-09-23 17:26 UTC, jasonbahl requested changes
Let's get a test. 

Here's one scenario we can test: 

```
create a post
create another post

query for 1st post by uri

assert first post is returned

add filter that returns post 2 instead

run the same query

assert post 2 is now returned
```

2022-09-24 23:06 UTC, justlevine commented
Sorry I know @jasonbahl suggested naming the filter `graphql_pre_resolve_uri_with_query_vars`, but I gotta disagree.

Not just because [I think that `graphql_pre_resolve_uri` should also pass `$extra_query_vars` ](https://github.com/wp-graphql/wp-graphql/issues/2515#issuecomment-1257076618), but also because its not communicating what makes this filter useful to the user: it happens towards the end of the `parse_request()` logic once `$this->wp` has been populated.

Perhaps naming the filter just `graphql_resolve_uri` makes sense here?

For similar reasons, I dont think that we need to or even should pass `$extra_query_vars` at this point of the method, since it's already been set (and possibly manipulated) on `$this->wp` .

Also, I think we should move it a few lines down to _after_ `do_action_ref_array( 'parse_request', [ &$this->wp ] );`, since thats also part of the `parse_request()` logic and the `$this->wp` population.

(Ideally, Id suggest putting `$node = apply_filters( 'graphql_pre_parse_request', null, $uri, $this->context, $this->wp, $extra_query_vars );` at the top of the method, and moving the existing `$node = apply_filters( 'graphql_pre_resolve_uri, null, $uri, $this->context, $this->wp );`  to after the `do_action_ref_array( ... )`, since IMO that makes the most sense semantically, but I'm not sure whether that would be considered a breaking - or even an unjustifiably annoying - change ).

2022-11-04 18:49 UTC, jasonbahl commented
closing as #2582 was merged

2022-11-04 18:49 UTC, closed without merging