feat: refactor mutation registration to use `WPMutationType`
wp-graphql/wp-graphql pull request #2563
Opened 2022-10-05 16:48 UTC by justlevine

What does this implement/fix? Explain your changes.
---------------------------------------------------
This PR refactors mutation registration to use the new `WPMutationType` class, in line with other GraphQL types and pseudo-types (like connections), paving the way for better extensibility.

### Details
- fix: `TermObjectUpdate` mutation names should start with lowercase.
- feat: Use `WPMutationType` to register mutations to the GraphQL schema.
- dev: Add the following filters: `graphql_wp_mutation_type_config`, `graphql_pre_mutate_and_get_payload`, `graphql_mutation_payload`.
- dev: Add the following action: `graphql_wp_mutation_type`.

Does this close any currently open issues?
------------------------------------------
…

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
- Explicit tests are not currently implemented. The overall functionality is tested via the existing mutation tests, and we cannot test the new actions/filters until a `deregister_graphql_mutation()` function is added to the API.
- Not sure if this invalidates #143 . We already have the existing `auth` and `isPrivate` config values, and we can use the new `graphql_pre_mutate_and_get_payload` to centralize other permission checks e.g.:
```php
add_filter( 'graphql_pre_mutate_and_get_payload',
  function( $payload, string $mutation_name, $mutateAndGetPayload, array $input, AppContext $context, ResolveInfo $info ) {
    if( ! current_user_can( 'do_something', $input['postId') ){
      throw new UserError( __( 'Sorry, bud', 'text-domain' ) );
    }
  
    // return null to run the normal $mutateAndGetPayload callback.
    // return null; 
  
    // use $mutateAndGetPayload with other functionality.
    do_something_before();
    $payload = $mutateAndGetPayload( $input, $context, $info );
    $payload = do_something_after( $payload );
  
    return $payload;
  },
10, 6 );
```
- This PR _does not_ refactor existing mutations. Action/Filter parity (#331) should occur separately.

Where has this been tested?
---------------------------
**Operating System:** Ubuntu 20.04 (WSL2 + devilbox + php 8.0.19)

**WordPress Version:** 6.0.2

2022-10-05 17:02 UTC, justlevine commented
No idea why the workflows arent triggering 🤔 tried closing the PR, pushing and reverting an empty commit, to no avail.

2022-11-11 23:03 UTC, jasonbahl commented on src/Type/WPMutationType.php
> +
```suggestion

$unfiltered_input = $args['input'];
```

2022-11-11 23:03 UTC, jasonbahl commented on src/Type/WPMutationType.php
> +			$input = apply_filters( 'graphql_mutation_input', $args['input'], $context, $info, $this->mutation_name );
```suggestion
			$input = apply_filters( 'graphql_mutation_input', $unfiltered_input, $context, $info, $this->mutation_name );
```

2022-11-11 23:03 UTC, jasonbahl commented on src/Type/WPMutationType.php
> +			do_action( 'graphql_mutation_response', $payload, $input, $context, $info, $this->mutation_name );
```suggestion
			do_action( 'graphql_mutation_response', $payload, $input, $unfiltered_input, $context, $info, $this->mutation_name );
```

2022-11-11 23:04 UTC, jasonbahl commented on src/Type/WPMutationType.php
> +			 * @param array $input The mutation input args, after being filtered by 'graphql_mutation_input'.
```suggestion
			 * @param array $input The mutation input args, after being filtered by 'graphql_mutation_input'.
			 * @param array $unfiltered_input The unfiltered input args of the mutation
```

2022-11-11 23:06 UTC, jasonbahl requested changes
@justlevine I left some suggested changes. 

It looks like the shape of the `graphql_mutation_response` changed in this PR. 

see current shape: https://github.com/wp-graphql/wp-graphql/blob/6de28e35389891781b8107e0404fa8e0c415c844/src/Registry/TypeRegistry.php#L1113

The `$filtered_input` and `$unfiltered_input` are both passed currently, but they weren't in this PR

2022-11-18 16:23 UTC, jasonbahl approved these changes

2022-11-18 17:45 UTC, merged